name: Unity License Activation ðŸ”‘

on:
  workflow_dispatch:

jobs:
  activation:
    name: Generate Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Request Activation File
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: "" # Empty license forces activation file generation
        with:
          targetPlatform: Android
          customParameters: -batchmode -nographics -createManualActivationFile -quit

      - name: Upload Activation File
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ./*.alf
