name: Unity License Activation ðŸ”‘

on:
  workflow_dispatch: # Allows you to run this manually

jobs:
  activation:
    name: Generate Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Request Activation File
        uses: game-ci/unity-request-activation-file@v2
        id: get_alf

      - name: Upload Activation File
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v2022.3.10f1.alf
          path: ${{ steps.get_alf.outputs.filePath }}
